import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { FormattedMessage, useIntl } from 'react-intl'
import Footer from '../components/Footer'
import Header from '../components/Header'
import { Cocktail } from '../models/Cocktail.model'
import { formatLocale } from '../utils'

interface IProps {
  drinks: Cocktail[]
}

const Home = ({ drinks }: IProps) => {

  const MAX_STR_LIMIT = 15;
  const router = useRouter();

  const [cocktail, setCocktail] = useState(drinks[0]);

  const { locale } : { locale?:string } = useRouter();
  const formattedLocale = formatLocale(locale!);

  const intl = useIntl();
  const title = intl.formatMessage({ id: "page.home.head.title" });

  const handleNewCocktail = (async () => {
    const { data } = await axios.get(`https://www.thecocktaildb.com/api/json/v1/1/random.php`);
    setCocktail(data.drinks[0]);
  })

  const handleSearch = async (name: string) => {
    console.log('name', name);

    const { data } = await axios.get(`https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${name}`);
    setCocktail(data.drinks?.length > 0 ? data.drinks[0] : null);

    if(cocktail === null) {
      const { data } = await axios.get(`https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Ordinary_Drink`);
      console.table(data.drinks);
      
    }
  }

  const handleChangeLang = (event: any) => {
    const { checked } = event.target
    const { pathname, query, asPath } = router;
    const { locales } = router;

    router.push({ pathname, query }, asPath, {locale: !checked ? locales![0]: locales![1] })
  }

  return (
    <div className='flex flex-col justify-between h-screen'>
      <Head>
        <title> {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header handleSearch={handleSearch} handleChangeLang={handleChangeLang} />

      <main className='w-screen'>
        {
          cocktail ? (
            <article className='p-8'>
              <figure className='flex flex-col justify-evenly  md:flex-row'>
                <Image className='md:rounded-full' src={cocktail.strDrinkThumb}  alt={`${cocktail.strDrink} image`}  priority={true} width={640} height={640} />
                <figcaption className='md:w-[50%] md:p-20'>
                  <div className='text-3xl pb-3 font-semibold'>{cocktail.strDrink}</div>
                  <div>
                    <p> <FormattedMessage id="page.home.cocktail.ingredienti" /> </p>
                    <ul>
                      {[...Array(MAX_STR_LIMIT)].filter((item, index) => cocktail[`strIngredient${index + 1}` as keyof typeof cocktail]).map((item, index) => (
                        <li key={index}>
                          - {`${cocktail[`strMeasure${index + 1}` as keyof typeof cocktail]} ${cocktail[`strIngredient${index + 1}` as keyof typeof cocktail]}`}
                        </li>
                      ))}
                    </ul>
                    <br />
                  </div>
                  <div>
                    {formattedLocale === 'it' ? cocktail?.strInstructionsIT : cocktail?.strInstructions }
                  </div>

                  <div>
                    <button onClick={handleNewCocktail}>
                      <FormattedMessage id='page.home.cocktail.new' />
                    </button>
                  </div>
                </figcaption>
              </figure>
            </article>
          ) : (
            <div>
              <div className='flex justify-center'>
                <FormattedMessage id='page.home.cocktail.no-result' />
              </div>
              <div className='inline-flex justify-between w-full p-8'>
                
                <figure className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                  <Image className='md:rounded-lg' src={'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg'}  alt={` image`}  priority={true} width={640} height={640} />
                  <figcaption>
                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
                    <p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
                    </figcaption>
                </figure>

                <figure className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                  <Image className='md:rounded-lg' src={'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg'}  alt={` image`}  priority={true} width={640} height={640} />
                  <figcaption>
                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
                    <p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
                    </figcaption>
                </figure>

                <figure className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                  <Image className='md:rounded-lg' src={'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg'}  alt={` image`}  priority={true} width={640} height={640} />
                  <figcaption>
                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
                    <p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
                    </figcaption>
                </figure>

              </div>

              <div className='inline-flex justify-between w-full p-8'>
                
              <figure className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                  <Image className='md:rounded-lg' src={'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg'}  alt={` image`}  priority={true} width={640} height={640} />
                  <figcaption>
                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
                    <p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
                    </figcaption>
                </figure>

                <figure className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                  <Image className='md:rounded-lg' src={'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg'}  alt={` image`}  priority={true} width={640} height={640} />
                  <figcaption>
                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
                    <p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
                    </figcaption>
                </figure>

                <figure className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                  <Image className='md:rounded-lg' src={'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg'}  alt={` image`}  priority={true} width={640} height={640} />
                  <figcaption>
                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
                    <p className="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
                    </figcaption>
                </figure>

              </div>
            </div>
          )
        }

      </main>

      <Footer />
    </div>
  )
}


export const getServerSideProps = async () => {
  const { data } = await axios.get(`https://www.thecocktaildb.com/api/json/v1/1/random.php`);

  // https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=17245

  return {
    props: {
      drinks: data.drinks
    }
  }
}

export default Home
